name       : Run Tests - Unit
on:
  push:


jobs:
  run-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Install Dependencies (using Poetry)
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/install-dependencies-poetry@main

      - name: Run Unit Tests
        uses: owasp-sbot/OSBot-GitHub-Actions/.github/actions/run-unit-tests@main
        with:
          package_name          : 'user_deployment_examples'
          #codecov_token         : ${{ secrets.CODECOV_TOKEN          }}
